### PR TITLE
Use stringer instead of string constants for time units 

### PR DESCRIPTION
**Pull request by arjunmahishi**
This is just a good practice I guess. Also, looks cleaner.

### CODE REVIEW

**Comment by arjunmahishi** [comment]
Since the actual string values of the unites are not really used so far, we can get rid of `timeunit_string.go`. Later the values are needed, we can just run `go generate`.

**Comment by arjunmahishi** [comment]
I've made another commit to organise the code a little more.

Changes:
- Move all the `Job` related code to `job.go`
- Move all the `Scheduler` related code to `scheduler.go`
- Move all the `type` and `var` to the top of the file
- Group multiple `var` together

**Comment by Streppel** [comment]
Thank you for your contribution @arjunmahishi. Will be looking into this in the next days

**Comment by JohnRoesler** [comment]
This looks good to me 👍

**Comment by JohnRoesler** [comment]
Next we should think about splitting out the test file similarly

**Comment by arjunmahishi** [comment]
Yes..

**Pull request merged**
