### PR TITLE
add github action to test on go version 12 & 13

### LINKED ISSUE #122: Set up CI for this project
We should set up a continuous integration system in this repository in order to prevent breaks on tests going live :) 

maybe we could use GitHub Actions for that?

### PR DESCRIPTION
**Pull request by JohnRoesler**
This will run tests using go versions 1.12 & 1.13 and for each it will test on Ubuntu, Mac OS and Windows all latest.

closes #122 

@preslavrachev @Streppel

### CODE REVIEW

**Comment by Streppel** [comment]
Sweet, thank you @JohnRoesler! Preslav said he'd do this using Travis but I'm sure he's ok with us using GitHub Actions for this :)

**Comment by JohnRoesler** [comment]
@Streppel just make sure it actions get enabled in the repo settings so it works 😄

**Comment by Streppel** [comment]
@JohnRoesler absolutely, I'm already contacting the project owner 👍🏻

**Comment by preslavrachev** [comment]
@Streppel @JohnRoesler Great job, guys! I got inspired by this to move my other Go projects away from Travis and over to GH Actions 😉

**Pull request merged**
