### PR TITLE
Adds production ready safety 

### PR DESCRIPTION
**Pull request by marcsantiago**
This PR was requested to be opened. It is a series of changes that make the code more production safe. In general it's not good practice to panic in source code that is meant to be imported. The user should be able to "catch" based on errors and not have to rely on defer recover

### CODE REVIEW

**Comment by fgblomqvist** [comment]
Would you consider your fork to still be in a good state? Need something like gocron for production and it seems like your fork would be the way to go (since this PR isn't getting taken care of).

**Comment by fgblomqvist** [comment]
Alright sounds good! Thanks for the quick response. I'll see what happens over the next few weeks and if I haven't heard anything from the original gocron maintainer by then, I might fork your repo and maintain it from there.

**Comment by vanugrah** [comment]
@jasonlvhit - can you have a look at this PR. @marcsantiago  Has done some wonderful work. Thank you both!

**Comment by Streppel** [comment]
@marcsantiago Hey there! Thank you very much for your effort here. I'd very much like to merge this PR, however we ended up getting some conflicts along the way... Could I help you manage this situation in order to merge this for once?

**Comment by marcsantiago** [comment]
@Streppel sure! It's been some time so the branches have diverged quite a bit.

**Comment by Streppel** [comment]
@marcsantiago amazing! Let's keep in touch in here so we can merge this with minimal friction :+1:  thank you!

**Comment by JohnRoesler** [comment]
If I might suggest, we could merge this into another branch (`feature-prod-safety) and then work on getting that ready for merge to master as it would allow collaboration on a gocron branch vs. opening PRs to @marcsantiago's repo to help get changes in.

**Comment by Streppel** [comment]
@marcsantiago I've changed the ongoing branch to a new one so we could help you with the merge! Let me know what you think :)

**Comment by marcsantiago** [comment]
Hey @Streppel Thanks! I'll take a look if I have time. However, this PR is so stale and it may not be relevant anymore. The branch I use, I use in production, I can't safely rebase these changes on my fork without potentially causing a disruption. My fork even has logic in place for distributed systems (on redis) to be able to run without job duplication/conflict. However, I like the new changes that are in master and may consider forking again for testing/modifications or creating a test branch from upstream/master to first see how capable it is with the production systems. Currently the code is so stable that before you reached out I forgot about the repo all together. Let me know what you think.

**Comment by Streppel** [comment]
Oh, I see @marcsantiago. No problem, that kind of stuff happens when PR's stay too much time laying around, I definitely understand your position; you've made some really good work on here! 

This being the case, I think me and John will tackle your changes and merge them with time, so you don't need to worry about the divergences, keep your fork as-is and keep your credits for the great work :) I hope that's ok

**Comment by marcsantiago** [comment]
That's amazing, thank you so much!

**Pull request merged**
